/*This file was generated by NativeWind. Do not edit!*/
const {
  NativeWindStyleSheet: _NativeWindStyleSheet
} = require("nativewind");
_NativeWindStyleSheet.create({
  styles: {
    "ribbon": {
      "transform": [{
        "translateY": -20
      }, {
        "translateX": 200
      }, {
        "rotate": "45deg"
      }]
    }
  },
  transforms: {
    "ribbon": true
  }
});