/*This file was generated by NativeWind. Do not edit!*/
const {
  NativeWindStyleSheet: _NativeWindStyleSheet
} = require("nativewind");
_NativeWindStyleSheet.create({
  styles: {
    "ribbontransform": {
      "transform": [{
        "translateY": -20
      }, {
        "translateX": 200
      }, {
        "rotate": "45deg"
      }]
    },
    "ribbon": {
      "backgroundColor": "rgb(200, 0, 0)",
      "height": 30,
      "justifyContent": "center",
      "alignItems": "center"
    },
    "ribbonstyle": {
      "backgroundColor": "rgb(200, 0, 0)",
      "height": 30,
      "justifyContent": "center",
      "alignItems": "center"
    }
  },
  transforms: {
    "ribbontransform": true,
    "ribbonstyle": true
  }
});